#!/usr/bin/env python3

import os
import sys

if len(sys.argv) < 2:
  print('Args required')
  exit(1)

function_name = sys.argv[1].split('/')[-1].split('.')[0]

print('Pushing function {}'.format(function_name))

zip_cmd = 'zip -r {}.zip '.format(function_name)

zip_cmd += ' '.join(sys.argv[1:])

print('ZIP: {}'.format(zip_cmd))

if os.system(zip_cmd) != 0:
  print('ZIP failed')
  exit(1)

aws_cmd = 'aws lambda update-function-code --function-name {} --zip-file fileb://{}'.format(function_name, function_name+'.zip')

print(aws_cmd)

if os.system(aws_cmd) != 0:
  print('aws failed')

remove_zip_cmd = 'rm {}.zip'.format(function_name)

os.system(remove_zip_cmd)
